version: '3.9'

configs:
  nginx_conf:
    file: ./nginx/nginx.conf

  cloudflare_logs_conf:
    file: ./nginx/cloudflare-logs.conf

  frontend_env:
    file: ./frontend.env

networks:
  default:

volumes:
  db:
  redis:
  rabbitmq:
  static:
  media:
  nginx_logs:

services:
  db:
    image: postgres:latest
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      

  redis:
    image: redis:alpine
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management

    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - type: volume
        source: rabbitmq
        target: /var/lib/rabbitmq
    networks:
      - default
    ports:
      - 15672:15672 # Web UI

  frontend:
    image: kyc_fe
    environment:
      - NODE_ENV=production
    configs:
      - source: frontend_env
        target: /app/.env.production.local
    entrypoint: yarn start
    volumes:
      - type: volume
        source: media
        target: /app/public/media
    networks:
      - default  

  backend:
    image: kyc_be
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/be
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234gyu
      - TURNSTILE_SITE_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - TURNSTILE_SECRET_KEY=0x4AAAAAAAC5YEVS87JdZtNreR865Ucl8Zw
      - JWT_SECRET=MC4CAQAwBQYDK2VwBCIEICSK61TR/2IsEtVNYJzcY3578mjg7y7OY2osGshdfsg
      - LOYALTINUM_API_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: static
        target: /app/static
      - type: volume
        source: media
        target: /app/media

    entrypoint: /app/scripts/entrypoint.dev.sh
    depends_on:
      - redis
      - rabbitmq
      - db
    networks:
      - default

  celery-worker:
    image: kyc_be
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/be
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234gyu
      - TURNSTILE_SITE_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - TURNSTILE_SECRET_KEY=0x4AAAAAAAC5YEVS87JdZtNreR865Ucl8Zw
      - JWT_SECRET=MC4CAQAwBQYDK2VwBCIEICSK61TR/2IsEtVNYJzcY3578mjg7y7OY2osGshdfsg
      - LOYALTINUM_API_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: static
        target: /app/static
      - type: volume
        source: media
        target: /app/media

    entrypoint: /app/scripts/celery-worker.sh

    depends_on:
      - backend

    networks:
      - default

  celery-beat:
    image: kyc_be

    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/be
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234gyu
      - TURNSTILE_SITE_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - TURNSTILE_SECRET_KEY=0x4AAAAAAAC5YEVS87JdZtNreR865Ucl8Zw
      - JWT_SECRET=MC4CAQAwBQYDK2VwBCIEICSK61TR/2IsEtVNYJzcY3578mjg7y7OY2osGshdfsg
      - LOYALTINUM_API_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: static
        target: /app/static
      - type: volume
        source: media
        target: /app/media

    entrypoint: /app/scripts/celery-beat.sh

    depends_on:
      - backend

    networks:
      - default

  celery-flower:
    image: kyc_be
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/be
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/1
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234gyu
      - TURNSTILE_SITE_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - TURNSTILE_SECRET_KEY=0x4AAAAAAAC5YEVS87JdZtNreR865Ucl8Zw
      - JWT_SECRET=MC4CAQAwBQYDK2VwBCIEICSK61TR/2IsEtVNYJzcY3578mjg7y7OY2osGshdfsg
      - LOYALTINUM_API_KEY=0x4AAAAAAAC5YHB57lGHydXb
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    ports:
      - 5545:5555

    volumes:
      - type: volume
        source: static
        target: /app/static
      - type: volume
        source: media
        target: /app/media

    entrypoint: /app/scripts/celery-flower.sh

    depends_on:
      - celery-worker

    networks:
      - default

  ocr:
    image: kyc_ocr
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/ocr
      - CELERY_RESULT_BACKEND=redis://redis:6379/5
      - REDIS_CACHE_URL=redis://redis:6379/4
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234ldsgki
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    ports:
      - 7000:8000
    volumes:
      - type: volume
        source: media
        target: /app/media
    entrypoint: /app/scripts/entrypoint.sh
    depends_on:
      - redis
      - rabbitmq
      - db
    networks:
      - default

  ocr-celery-worker:
    image: kyc_ocr
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/ocr
      - CELERY_RESULT_BACKEND=redis://redis:6379/5
      - REDIS_CACHE_URL=redis://redis:6379/4
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234ldsgki
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: media
        target: /app/media
    command: celery -A project worker -l info -Ofair 
    

    depends_on:
      - ocr
    networks:
      - default

  ocr-celery-beat:
    image: kyc_ocr
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/ocr
      - CELERY_RESULT_BACKEND=redis://redis:6379/5
      - REDIS_CACHE_URL=redis://redis:6379/4
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234ldsgki
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: media
        target: /app/media
    entrypoint: /app/scripts/celery-beat.sh
    depends_on:
      - ocr
    networks:
      - default

  ocr-celery-flower:
    image: kyc_ocr
    environment:
      - SECRET_KEY=nh_zk9@rql9nsjo41n1z5(%%oe_(marz$*ze#pw&2e-dor2%nt
      - DEBUG=True
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672/ocr
      - CELERY_RESULT_BACKEND=redis://redis:6379/5
      - REDIS_CACHE_URL=redis://redis:6379/4
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - EMAIL_HOST=mail.sidramail.com
      - EMAIL_PORT=587
      - EMAIL_FROM=noreply@kycport.com
      - EMAIL_USER=noreply@kycport.com
      - EMAIL_PASSWORD=kvk@1234ldsgki
      - SITE_URL=http://localhost
      - OCR_KEY=fea6c5af2a8441d54adf79bf9a21ca1a
    volumes:
      - type: volume
        source: media
        target: /app/media
    ports:
      - 5546:5555
    entrypoint: /app/scripts/celery-flower.sh
    depends_on:
      - ocr-celery-worker
    networks:
      - default

  kycport-dev-proxy:
    image: nginx:latest
    volumes:
      - type: volume
        source: nginx_logs
        target: /var/log/nginx
      - type: volume
        source: static
        target: /var/www/html/static
      - type: volume
        source: media
        target: /var/www/html/media

    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf

      - source: cloudflare_logs_conf
        target: /etc/nginx/cloudflare-logs.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

    networks:
      - default

